# Changes here will be overwritten by Copier
_commit: 497ef93
_src_path: gh:audivir/copier-template
description: Create Dose-Response-Curves from csv files
github_org: audivir
project_name: dose-response
project_slug: dose_response
project_type: python
publishable: true
